### PR TITLE
George has stepped down

### PR DESCRIPTION
**Pull request by gwils**

### CODE REVIEW

**Comment by treeowl** [comment]
You obviously have the right to step down, but I think it could be helpful to the community if you'd say a few words about why.

**Comment by gwils** [comment]
I wrote a few words about that here in the announcement on the public CLC google group: https://groups.google.com/g/haskell-core-libraries/c/WG-tK4J9bIk/m/iV_Pw3N2CgAJ
Essentially I agreed to extend my term by one year during the CLC reformation, but I've now realised that another year isn't sustainable for me. I've had declining free time recently for personal reasons, and I've recently taken a non-Haskell job, which will make it more of an uphill battle to keep up with the community goings-on.
I've also noticed non-committee members paying more attention and offering more input on CLC issues than I have, so it seems appropriate to make space for some of these voices to step up to the committee.

**Comment by treeowl** [comment]
Thank you. Best of luck on your next endeavor.

**Review by Bodigrim — APPROVED** [review]

**Comment by Bodigrim** [comment]
Many thanks for your time and work during these years, @gwils!

**Pull request merged**
