### PR TITLE
Mention (!! 0) as a drop-in replacement for Data.List.head

### PR DESCRIPTION
**Pull request by Bodigrim**
I'm somewhat unsure how to frame this option. I do not feel like I want to encourage it, but it's certain from [this thread](https://www.reddit.com/r/haskell/comments/18ngucn/comment/kebc9j6/?utm_source=reddit&utm_medium=web2x&context=3) that some people find this workaround useful.

### CODE REVIEW

**Comment by hasufell** [comment]
It's getting a bit bizarre, though. 

Generally speaking, whenever I provide unsafe API in my packages, I don't advertise it prominently.

Yes, I want users to spend time looking for it.

While I strongly disagree with the head/tail warnings, maybe pointing users to partial alternatives is undermining the original mission.

Just saying.

**Comment by Ericson2314** [comment]
> Maybe pointing users to partial alternatives is undermining the original mission.

Yes it sure is.

**Review by tomjaguarpaw — APPROVED** [review]
It's much cheaper to change the migration guide than to change `base` :) I suggest we add this suggestion and revisit the decision later if we conclude it's not a good idea and we want to change it back.

On the other hand. if deprecating `(!!)` is in the forseeable future then we probably shouldn't make this suggestion.

**Comment by parsonsmatt** [comment]
The ability to disable the warning on a per-file basis or per-project basis for those that want partial functions seems like a perfectly acceptable workaround.

We definitely *shouldn't* be pushing people towards `(!!)` - in addition to a potential for runtime errors, it's also often an indication that the wrong datastructure is in use.

**Comment by Bodigrim** [comment]
@parsonsmatt @hasufell @mixphix my view is that a migration guide should be "politically-neutral" and list as many migration strategies as possible. 

Some people take a view difficult to accomodate: "Module-wise warnings are not good enough: I don't want to disable `-Wno-x-partial` warning in entire module, because I find it generally useful and it (potentially) covers multiple functions. I want to suppress only this particular one invocation of `head` and I don't want to rewrite it in a total manner". (Do I personally find such stance reasonable? No. But) In such case `(!! 0)` could be helpful.

I've updated the wording, what do you think about it now?

**Comment by Bodigrim** [comment]
@parsonsmatt @hasufell @mixphix I'm keen to hear your opinion on the wording above.

**Comment by parsonsmatt** [comment]
I disagree with including it, on the basis that, in some ideal future, `(!!)` is *also* given a `WARNING` for partiality. This just punts the issue.

If you're a sufficiently experienced Haskeller that you know when and how `head` is truly safe to call, then you're *also* able to figure out how to do it *without* an ugly `xs !! 0` call, or figure that out yourself. Writing out all the various ways to write `head` without warnings feels unreasonable.

I still think we should have some variant of [`unsafeHead :: HasCallStack => String -> [a] -> a`](https://www.stackage.org/lts-22.12/hoogle?q=String+-%3E+%5Ba%5D+-%3E+a) in `Data.List`. Users can be guided to use that if they think it's a good idea, and also augment the precondition that was violated (if it ever does `error`).

**Comment by Bodigrim** [comment]
Fair enough, closing. 

To be clear: we do not need a consensus to update a migration guide and I could have asked for a vote, but it's my free will to withdraw in the current circumstances.

**Pull request closed without merging**
